version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox

# fetch_data: &fetch_data
#   run:
#     name: Set script permissions and fetch data
#     command: |
#       source venv/bin/activate
#       chmod +x ./scripts/fetch_kaggle_dataset.sh
#       ./scripts/fetch_kaggle_dataset.sh

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/david/api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  section_07_deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App (You must set RAILWAY_TOKEN env var)
          command: |
            cd section-07-ci-and-publishing/house-prices-api && railway up --detach

  test_and_upload_model:
    <<: *defaults
    working_directory: ~/project/david/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      # - run:
      #     name: Fetch the data
      #     command: |
      #       tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model
          command: |
            chmod +x ./publish_model.sh
            tox -e publish_model

  train_and_upload_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run: 
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
      # - *fetch_data
      - run: 
          name: Train model
          command: |
            . venv/bin/activate
            PYTHONPATH=./packages/classifier_model python3 packages/classifier_model/classifier_model/train_pipeline.py
      - run: 
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./packages/classifier_model/

  publish_docker_image_to_aws:
    <<: *defaults
    working_directory: ~/project/david/api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publishing docker image to aws ECR
          command: |
            sudo pip install awscli
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            chmod +x ./build_docker_image_aws.sh
            ./scripts/publish_model.sh

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - test_app
      - section_07_deploy_app_to_railway:
          requires:
            - test_app
          filters:
            branches:
              only:
                - master
                - demo
      # upload after git tags are created
      - test_and_upload_model
          # <<: *tags_only
      - publish_docker_image_to_aws
      # - section_08_deploy_app_container_via_railway:
      #    filters:
      #      branches:
      #        only:
      #          - master
      #          - demo